// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT8WK7cS8a-bbDIXOz3Cp4N2mcpncoxts',
    appId: '1:539026047934:web:70b55dfe1112c6cfecefef',
    messagingSenderId: '539026047934',
    projectId: 'lifemate-9147d',
    authDomain: 'lifemate-9147d.firebaseapp.com',
    storageBucket: 'lifemate-9147d.appspot.com',
    measurementId: 'G-5P3JQVEY1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAiFMUZBRjSzOxfAUa6ZQQUM729R2NuXA',
    appId: '1:539026047934:android:02c33475bd4fefd1ecefef',
    messagingSenderId: '539026047934',
    projectId: 'lifemate-9147d',
    storageBucket: 'lifemate-9147d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5ZplzPsXwUTcn0Y0GY1Lt7skLRtEaNvI',
    appId: '1:539026047934:ios:99db027e28989931ecefef',
    messagingSenderId: '539026047934',
    projectId: 'lifemate-9147d',
    storageBucket: 'lifemate-9147d.appspot.com',
    iosBundleId: 'com.example.lifemate',
  );
}
